name: Game Removal
description: Request to take down a game from Railin'
labels: ["REMOVAL"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Just in case I need proof of ownership.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: name
    attributes:
      label: Games Name
      description: The name of your game.
      placeholder: ex. Fortnite
    validations:
      required: false
  - type: textarea
    id: reason
    attributes:
      label: Reasoning For Takedown
      description: Please explain why you would like to take down your game.
      placeholder: ex. I would like to take my game down because a hotdogs a sandwhich
      render: shell
