name: "Game Removal"
about: "Request to take down a game from Railin'"
title: ''
labels: ["REMOVAL"]
assignees: ''
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Just in case I need proof of ownership.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: name
    attributes:
      label: Games Name
      description: The name of your game.
      placeholder: ex. Fortnite
    validations:
      required: false
  - type: textarea
    id: reason
    attributes:
      label: Reasoning For Takedown
      description: Please explain why you would like to take down your game.
      render: shell
